server:
  port: 9092
  
spring:
  application:
    name: book-service
  data:
    mongodb:
      uri: mongodb://${MONGO_CONTAINER}:8081/${MONGO_INITDB_DATABASE}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE} #http://eureka-server:8761/eureka
    region: default
    registryFetchIntervalSeconds: 5
