spring:
  application:
    name: gateway  

server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE} #http://eureka-server:8761/eureka
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    discovery:
      path: /eureka-server/**
      sensitive-headers: Set-Cookie,Authorization
      url: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE} #http://eureka-server:8761/eureka
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization      

hystrix:
  command:
    discovery:
      execution:
        isolation:
          thread:
            timeoutMilliseconds: 600000
