spring:
  application:
    name: gateway

server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    discovery:
      path: /eureka-server/**
      sensitive-headers: Set-Cookie,Authorization
      url: ${ZUUL_ROUTES_DISCOVERY_URL} #http://eureka-server:8082

hystrix:
  command:
    discovery:
      execution:
        isolation:
          thread:
            timeoutMilliseconds: 600000
